# Generated by Django 5.1.7 on 2025-03-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=250, null=True)),
                ('prazo', models.DateField()),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('situacao', models.CharField(choices=[('nova', 'Nova'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='nova', max_length=20)),
            ],
        ),
    ]
